version: "3"

services:
  postgres-test:
    container_name: postgres-test
    platform: linux/amd64
    image: postgres:14.7
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/pg_data
      - POSTGRES_HOST_AUTH_METHOD=password
      - PGPORT=5433
    command: postgres -c 'max_connections=1000'
    ports:
      - 5433:5433
    restart: always
